# Pandas series

In [57]:
import pandas as pd
import numpy as np
from numpy.random import randn

In [33]:
my_series = [1, 88, 21, 233]
my_new = pd.Series(my_series) 
print(my_new)

0      1
1     88
2     21
3    233
dtype: int64

In [ ]:
my_index = ['A','B','C','D'] # ye sary index hain
my_new = pd.Series (my_series,my_index) #pd.Series() Pandas ka function hai, jo ek Series object banata hai.
#A Pandas Series ek 1-dimensional labeled array hota hai (like a column of data).
print(my_new)
my_new['B'] # is me B mane index hai is me jo be number ye value ho gi wo print ho jya gi

A      1
B     88
C     21
D    233
dtype: int64

np.int64(88)

# Key Value Dictionary

In [56]:
cars = {"Honda":21 , "Tesla":30 , "BMW" : 10 }
my_cars = pd.Series(cars)
print(my_cars)
cars["Honda"]

Honda    21
Tesla    30
BMW      10
dtype: int64

21

# DataFrame

In [58]:
my_data = randn(4,3) # 4 rows hain 3 column
my_row = ['A','B','C','D']
my_col = ['Monday','Tuesday','Wednesday']

my_df = pd.DataFrame(my_data,my_row,my_col)
print(my_df)

     Monday   Tuesday  Wednesday
A -0.932785 -0.402906   1.579316
B  0.148169  1.147266   0.363800
C -1.022409  0.632465   1.270805
D  1.545672  1.236077   1.646683

In [98]:
my_df2 = pd.read_csv('dog_info.csv')
print(my_df2)

      breed pentname     color  ownernumber  age  gender
0  Labrador      Max     Black          101    3    Male
1    Poodle    Bella     White          102    5  Female
2   Bulldog  Charlie     Brown          103    2    Male
3    Beagle     Lucy  Tricolor          104    4  Female

In [ ]:
my_df2.loc[2] # location likhna ka lia hum loc use krta hain ye mane row 2 print ki hain
my_df2.loc[[0,8]] # multiple rows print ka lia

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Compact Printer Air Advanced Digital,Situation organization these memory much off.,"Garner, Boyle and Flynn",Books & Stationery,265,USD,774,2091465262179,ForestGreen,Large,pre_order,56
8,9,Eco Radio,Know father for act let.,"Edwards, Odonnell and Conley",Skincare,454,USD,499,1773215338624,DimGray,Medium,pre_order,88

In [97]:

my_df2.head() # 1st 5 rows ka lia
my_df2.tail() # last 4 rows ka lia
my_df2.tail(9) # last ki 9 rows
my_df2.info # Dataframe ki infomation ka lia
my_df2.shape 
my_df2.ndim # ye dimension pr hai
my_df2.dtypes # colum ki datatype ka lia
my_df2.describe() # complete data ko describe kr deta hai 
# my_df2[""].describe() yeh specfice column ko describe krna ka lia use hota hai

       ownernumber
count     4.000000
mean    102.500000
std       1.290994
min     101.000000
25%     101.750000
50%     102.500000
75%     103.250000
max     104.000000